image: rust:latest

stages:
  - check
  - build

rust-clippy:
  stage: check
  allow_failure: true
  script:
    - rustup component add clippy
    - cargo clippy

cargo-fmt:
  stage: check
  script:
    - rustup component add rustfmt
    - cargo fmt --check

rust-latest:
  stage: build
  script:
    - cargo build --release